version: '3'

services:    
   arangodb_db_container:
    image: arangodb:latest
    container_name: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - 8529:8529
    volumes:
      - ~/volumes/arangodb4/container:/var/lib/arangodb3    
      - ~/volumes/arangodb4/data_container:/var/lib/arangodb3-apps  
      
  gate:
    build: ./gate
    container_name: gate
    ports:
      - "2024:2024"
    networks:
      - telnet
      
  telex:
    image: telex
    build: ./telex
    container_name: telex
    ports:
      - "2025:2025"
    networks:
      - telnet      
  
   driver:
    image: driver
    build: ./driver
    container_name: telex
    ports:
      - "2026:2026"
    networks:
      - telnet
      

      
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8405:80"
      - "8404:8404"
    networks:
      - telnet
      
volumes:
  arangodb_data_container:
  arangodb_apps_data_container:

networks:
  telnet:
