version: '3'
services:     
  
  gate:
    build: ./gate
    container_name: gate
    ports:
      - '2024:2024'
    networks:
      - telex_mongo-network
      
  telex:
    image: telex
    build: ./telex
    container_name: telex
    ports:
      - '2025:2025'
    networks:
      - telex_mongo-network

  driver:
    image: driver
    build: ./driver
    env_file: .env    
    container_name: driver  
    ports:
      - '2026:2026'      
    networks:
      - telex_mongo-network

      
  haproxy:
    image: 'haproxy:latest'
    container_name: haproxy
    volumes:
      - './haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'
    networks:
      - telex_mongo-network
    ports:
      - '8405:80'
      - '8404:8404'


networks:
  telex_mongo-network:
    name: telex_mongo-network
    external: true