services: 
  
  gate:
    build: ./gate
    container_name: gate
    env_file: ./gate/.env
    ports:
      - '2024:2024'
    networks:
      - platform
      
  telex:
    image: telex
    build: ./telex
    container_name: telex
    env_file: ./telex/.env
    ports:
      - '2025:2025'
    networks:
      - platform

  driver:
    image: driver
    build: ./driver
    env_file: ./driver/.env
    container_name: driver  
    ports:
      - '2026:2026'      
    networks:
      - platform
      
  river:
    image: river
    build: ./river
    env_file: ./river/.env
    container_name: river  
    ports:
      - '2027:2027'      
    networks:
      - platform
      
      
  subscriber:
    image: subscriber
    build: ./subscriber
    env_file: ./subscriber/.env
    container_name: subscriber  
    ports:
      - '2028:2028'      
    networks:
      - platform


      
  haproxy:
    image: 'haproxy:latest'
    container_name: haproxy
    volumes:
      - './haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'
    networks:
      - platform
    ports:
      - '8405:80'
      - '8404:8404'


networks:
  platform:
    driver: bridge
    ipam:
      driver: default