management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

      
server:
   port: 2025
    
spring:    
  application:
    name: telex


logging:
    level:
      root: INFO
      io.project.app.telex: INFO
