management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  security:
    enabled: false
  server:
    port: 3025
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    probes:
      enabled: true
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

      
server:
   port: 2025
    
spring:    
  application:
    name: telex


logging:
    level:
      root: INFO
      io.project.app: INFO
