management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  security:
    enabled: false
  server:
    port: 3027
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    probes:
      enabled: true
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'
      
server:
  http2:
    enabled: true
  port: 2027 
  compression:
    enabled: true
    mime-types: >-
      text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    
spring:    
  application:
    name: river
    
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: admin
      auto-index-creation: true
      uri: ${MONGO_URI}
      primary:
         database: ${MONGO_DATABASE}
         uri: ${MONGO_URI}

logging:
    level:
      root: INFO
      io.project.app.river: INFO
