management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

      
server:
  http2:
    enabled: true
  port: 2027 
  compression:
    enabled: true
    mime-types: >-
      text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    
spring:    
  application:
    name: river
    
  data:
    mongodb:  
      auto-index-creation: true
      database: riverDB
      uri: mongodb://uber:uber123@mongo1:27017/riverDB?replicaSet=dbrs&authSource=admin&connectTimeoutMS=10000&minPoolSize=0&maxPoolSize=3000&maxIdleTimeMS=300000
   #  uri: mongodb://uber:uber123@mongo1:27017/riverDB?replicaSet=dbrs&readPreference=primaryPreferred&authSource=admin&connectTimeoutMS=10000&minPoolSize=0&maxPoolSize=3000&maxIdleTimeMS=300000


logging:
    level:
      root: INFO
      io.project.app.river: INFO
