management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

      
server:
  http2:
    enabled: true
  port: 2028
  compression:
    enabled: true
    mime-types: >-
      text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    
spring:    
  application:
    name: subscriber


logging:
    level:
      root: INFO
      io.project.app.subscriber: INFO
