management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

      
server:
   port: 2026
    
spring:    
  application:
    name: driver    
    
  data:
    mongodb:
     primary:
        auto-index-creation: true
        database: driverDB        
        uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongonode:27017/driverDB?connectTimeoutMS=3000&minPoolSize=0&maxPoolSize=200&maxIdleTimeMS=9000
    

logging:
    level:
      root: INFO
      io.project.app.driver: INFO
