management:
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'

      
server:
  http2:
    enabled: true
  port: 2026
  servlet:
    session:
      timeout: 10m
  undertow:
    buffer-size: 40960
    no-request-timeout: 5000
  compression:
    enabled: true
    mime-types: >-
      text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    
spring:    
  application:
    name: driver

  data:
    mongodb:
      database: driverDB
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      authentication-database: admin
      primary:
         auto-index-creation: true
         database: driverDB
         uri: mongodb://uber:uber123@mongo1:27017/driverDB?replicaSet=rs0&readPreference=primaryPreferred&authSource=admin     

   
   # mongodb://uber:uber123@localhost:27017/driverDB?readPreference=primaryPreferred&authSource=admin


logging:
    level:
      root: INFO
      io.project.app.driver: INFO
